-- Drop all users
DROP USER [chad.lagos];
DROP USER [george.hughen];
DROP USER [jeffrey.chadbourne];
DROP USER [john.cartales];
DROP USER [john.warner];
DROP USER [michael.sun];
DROP USER [michael.zhang];
DROP USER [NMSLogAnalyzer];
DROP USER [paul.healey];
DROP USER [SQLMonitor];
DROP USER [stephen.oliveira];
DROP USER [wade.poust];
DROP ROLE [NMSDeveloper];

-- Drop all constraints
ALTER TABLE dbo.SASAccountStatus DROP CONSTRAINT FK_AccountId;
ALTER TABLE dbo.AccountInList DROP CONSTRAINT FK_AccountInList_Account;
ALTER TABLE dbo.AccountOpenIDSetting DROP CONSTRAINT FK_AccountOpenIDSetting_Account;
ALTER TABLE dbo.AccountProductMap DROP CONSTRAINT FK_AccountProductMap_Account;
ALTER TABLE dbo.AlertEvents DROP CONSTRAINT FK_AlertEvents_Account;
ALTER TABLE dbo.AuditEvents DROP CONSTRAINT FK_AuditEvents_Account;
ALTER TABLE dbo.AutoProvisioning DROP CONSTRAINT FK_AutoProvisioning_Account;
ALTER TABLE dbo.ConvertedUsageTransaction DROP CONSTRAINT FK_ConvertedUsageTransaction_Account;
ALTER TABLE dbo.ConvertedUsageTransaction DROP CONSTRAINT FK_ConvertedUsageTransaction_OEM;
ALTER TABLE dbo.ConvertedUsageTransaction DROP CONSTRAINT FK_ConvertedUsageTransaction_Product;
ALTER TABLE dbo.ConvertedUsageTransaction DROP CONSTRAINT FK_ConvertedUsageTransaction_User;
ALTER TABLE dbo.CredentialToken DROP CONSTRAINT FK_CredentialsToken_Account;
ALTER TABLE dbo.CustomersToTransco DROP CONSTRAINT FK_CustomersToTransco_Accounts;
ALTER TABLE dbo.DictationUpload DROP CONSTRAINT FK_DictationUpload_Account;
ALTER TABLE dbo.Domain DROP CONSTRAINT FK_Domain_Account;
ALTER TABLE dbo.DownloadedPackages DROP CONSTRAINT FK_DownloadedPackages_Account;
ALTER TABLE dbo.DragonConvertedUsageTransaction DROP CONSTRAINT FK_DragonConvertedUsageTransaction_Account;
ALTER TABLE dbo.DragonProfileLocation DROP CONSTRAINT FK_DragonProfileLocation_Account;
ALTER TABLE dbo.EID DROP CONSTRAINT FK_EID_Account;
ALTER TABLE dbo.FLEXnetTransactions DROP CONSTRAINT FK_FLEXnetTransactions_Account;
ALTER TABLE dbo.Groups DROP CONSTRAINT FK_Groups_Account;
ALTER TABLE dbo.Groups DROP CONSTRAINT FK_Groups_Role;
ALTER TABLE dbo.Groups DROP CONSTRAINT FK_Groups_Sites;
ALTER TABLE dbo.License DROP CONSTRAINT FK_License_Account;
ALTER TABLE dbo.LicenseUsage DROP CONSTRAINT FK_LicenseUsage_Account;
ALTER TABLE dbo.LoginHistory DROP CONSTRAINT FK_LoginHistory_Account;
ALTER TABLE dbo.PatientListAudit DROP CONSTRAINT FK_PatientListAudit_Account;
ALTER TABLE dbo.PONodeData DROP CONSTRAINT FK_PONodeData_fkAccount;
ALTER TABLE dbo.POTaskData DROP CONSTRAINT FK_POTaskData_fkAccount;
ALTER TABLE dbo.Product DROP CONSTRAINT FK_Product_OEM;
ALTER TABLE dbo.Role DROP CONSTRAINT FK_Role_Product;
ALTER TABLE dbo.ServerLog DROP CONSTRAINT FK_ServerLog_Account;
ALTER TABLE dbo.Settings DROP CONSTRAINT FK_Settings_Account;
ALTER TABLE dbo.Sites DROP CONSTRAINT FK_Sites_Account;
ALTER TABLE dbo.Sites DROP CONSTRAINT FK_Sites_BillingData;
ALTER TABLE dbo.Sites DROP CONSTRAINT FK_Sites_DragonProfileLocation;
ALTER TABLE dbo.SMTPMessage DROP CONSTRAINT FK_SMTPMessages_Account;
ALTER TABLE dbo.SUSTasks DROP CONSTRAINT FK_SUSTasks_Account;
ALTER TABLE dbo.SystemConfiguration DROP CONSTRAINT FK_System_Account;
ALTER TABLE dbo.Users DROP CONSTRAINT FK_Users_Account;

-- Drop all views
DROP VIEW dbo.ClientVersionInformationReporting;
DROP VIEW dbo.DragonSpeechUsageTrend;
DROP VIEW dbo.GlobalGrants;
DROP VIEW dbo.GroupGrants;
DROP VIEW dbo.GroupGrantsFromWildcardsIndexedView;
DROP VIEW dbo.GroupGrantsNoWildcards;
DROP VIEW dbo.GroupUserMap;
DROP VIEW dbo.LicenseSummary;
DROP VIEW dbo.OrganizationGrants;
DROP VIEW dbo.OrganizationGrantsNoWildcards;
DROP VIEW dbo.OrgGrantsFromWildcardsIndexedView;
DROP VIEW dbo.OrgUserCounts;
DROP VIEW dbo.PrincipalGrants;
DROP VIEW dbo.SiteGrants;
DROP VIEW dbo.SiteGrantsFromWildcardsIndexedView;
DROP VIEW dbo.SiteGrantsNoWildcards;
DROP VIEW dbo.SpeechUsageTrend;

-- Drop all tables except ConvertedUsageTransaction
DROP TABLE dbo.Account;
DROP TABLE dbo.AccountInList;
DROP TABLE dbo.AccountOpenIDSetting;
DROP TABLE dbo.AccountProductMap;
DROP TABLE dbo.AlertEvents;
DROP TABLE dbo.AuditEvents;
DROP TABLE dbo.AuditFramework;
DROP TABLE dbo.AutoProvisioning;
DROP TABLE dbo.BillingData;
DROP TABLE dbo.BlockUpload;
DROP TABLE dbo.ClientLog;
DROP TABLE dbo.ClientVersionInformation;
DROP TABLE dbo.Cluster;
DROP TABLE dbo.CommandLog;
DROP TABLE dbo.Connectors;
DROP TABLE dbo.CredentialNHID;
DROP TABLE dbo.CredentialNTLM;
DROP TABLE dbo.CredentialOrgLogins;
DROP TABLE dbo.CredentialSystem;
DROP TABLE dbo.CredentialToken;
DROP TABLE dbo.CustomersToTransco;
DROP TABLE dbo.DatabaseSchemaNumber;
DROP TABLE dbo.DictationUpload;
DROP TABLE dbo.DMAadvice;
DROP TABLE dbo.DMAadviceSpecifierLicenseMap;
DROP TABLE dbo.DMAadviceSpecifiers;
DROP TABLE dbo.DMASpecifierFilters;
DROP TABLE dbo.Domain;
DROP TABLE dbo.DownloadedPackages;
DROP TABLE dbo.DragonConvertedUsageTransaction;
DROP TABLE dbo.DragonMedicalDatabaseSchemaNumber;
DROP TABLE dbo.DragonProfileLocation;
DROP TABLE dbo.DragonProfileLocationSpeechNodeMap;
DROP TABLE dbo.EID;
DROP TABLE dbo.EmailVerificationKey;
DROP TABLE dbo.ErrorLogging;
DROP TABLE dbo.EventRegistration;
DROP TABLE dbo.FLEXnetTransactions;
DROP TABLE dbo.GrantDefinition;
DROP TABLE dbo.GrantedRights;
DROP TABLE dbo.Grants;
DROP TABLE dbo.GroupEnrollment;
DROP TABLE dbo.GroupInList;
DROP TABLE dbo.Groups;
DROP TABLE dbo.HIMDatabaseSchemaNumber;
DROP TABLE dbo.HIMSession;
DROP TABLE dbo.HIMTemplateLanguageModel;
DROP TABLE dbo.HIMWorktype;
DROP TABLE dbo.HIMWorktypeTemplateMapping;
DROP TABLE dbo.KilledProcess;
DROP TABLE dbo.KPITransaction;
DROP TABLE dbo.License;
DROP TABLE dbo.LicenseKey;
DROP TABLE dbo.LicenseProvisioning;
DROP TABLE dbo.LicenseType;
DROP TABLE dbo.LicenseUsage;
DROP TABLE dbo.Loadable;
DROP TABLE dbo.LoginHistory;
DROP TABLE dbo.Messages;
DROP TABLE dbo.NASSchedule;
DROP TABLE dbo.NHIDAccountReset;
DROP TABLE dbo.NHIDDatabaseSchemaNumber;
DROP TABLE dbo.NHIDImage;
DROP TABLE dbo.NHIDOptOut;
DROP TABLE dbo.NHIDPendingActivation;
DROP TABLE dbo.NHIDStandardApplication;
DROP TABLE dbo.NHIDToken;
DROP TABLE dbo.NMSNodes;
DROP TABLE dbo.Notification;
DROP TABLE dbo.NotificationTargetNodes;
DROP TABLE dbo.NotificationTargets;
DROP TABLE dbo.OEM;
DROP TABLE dbo.PasswordHistory;
DROP TABLE dbo.PasswordResetKey;
DROP TABLE dbo.PatientListAudit;
DROP TABLE dbo.POMedicationUpdate;
DROP TABLE dbo.PONodeData;
DROP TABLE dbo.PONodeWorkItems;
DROP TABLE dbo.POTaskData;
DROP TABLE dbo.POTaskSchedule;
DROP TABLE dbo.Privilege;
DROP TABLE dbo.PrivilegeDefinition;
DROP TABLE dbo.Product;
DROP TABLE dbo.ProviderRoleMapping;
DROP TABLE dbo.Rights;
DROP TABLE dbo.Role;
DROP TABLE dbo.RolePrivilegeMap;
DROP TABLE dbo.RoleRightsMap;
DROP TABLE dbo.SASAccountStatus;
DROP TABLE dbo.SASExclusiveTasks;
DROP TABLE dbo.SelectionRules;
DROP TABLE dbo.ServerLog;
DROP TABLE dbo.Session;
DROP TABLE dbo.Settings;
DROP TABLE dbo.SiteGroupEnrollment;
DROP TABLE dbo.SiteInList;
DROP TABLE dbo.Sites;
DROP TABLE dbo.SMTPMessage;
DROP TABLE dbo.SpeechCommand;
DROP TABLE dbo.SpeechCommandNames;
DROP TABLE dbo.SpeechList;
DROP TABLE dbo.SpeechMetaData;
DROP TABLE dbo.SpeechWord;
DROP TABLE dbo.SpeechWordTraining;
DROP TABLE dbo.SUSTaskResults;
DROP TABLE dbo.SUSTasks;
DROP TABLE dbo.SystemConfiguration;
DROP TABLE dbo.TreatedVistId;
DROP TABLE dbo.UpdateablePackages;
DROP TABLE dbo.UsageTransaction;
DROP TABLE dbo.Users;
DROP TABLE dbo.VisitIdException;
DROP TABLE dbo.WhoIsActiveHistory;
DROP TABLE SQLSentry.ProcedureStats_1_63B4EEABC64A85B308135476FBFCDFCF;
DROP TABLE SQLSentry.ProcedureStats_1_D82B70F1A9398C757577D032D11D0B6E;
DROP TABLE SQLSentry.ProcedureStats_2_63B4EEABC64A85B308135476FBFCDFCF;
DROP TABLE SQLSentry.ProcedureStats_2_D82B70F1A9398C757577D032D11D0B6E;
DROP TABLE SQLSentry.QueryStats_1_63B4EEABC64A85B308135476FBFCDFCF;
DROP TABLE SQLSentry.QueryStats_1_D82B70F1A9398C757577D032D11D0B6E;
DROP TABLE SQLSentry.QueryStats_2_63B4EEABC64A85B308135476FBFCDFCF;
DROP TABLE SQLSentry.QueryStats_2_D82B70F1A9398C757577D032D11D0B6E;
DROP TABLE SQLSentry.SQLSentryObjectVersion_20;

-- Defragment indexes
DROP INDEX [ConvertedUsageTransaction].[IX_ConvertedUsageTransaction_fkUser];
DROP INDEX [dbo].[ConvertedUsageTransaction].[IX_ConvertedUsageTransaction_fkAccount_fkUser_Date];
CREATE NONCLUSTERED INDEX [IX_ConvertedUsageTransaction_fkAccount_fkUser_Date] ON [dbo].[ConvertedUsageTransaction] ([fkAccount] ASC, [fkUser] ASC, [DateOfTransaction] ASC);

ALTER INDEX IX_ConvertedUsageTransaction_UserLogin_UserGuid ON ConvertedUsageTransaction REBUILD WITH (ONLINE = OFF);
ALTER INDEX IX_ConvertedUsageTransaction_UserGuid ON ConvertedUsageTransaction REBUILD WITH (ONLINE = OFF);
ALTER INDEX IX_ConvertedUsageTransaction_fkOEM ON ConvertedUsageTransaction REBUILD WITH (ONLINE = OFF);
ALTER INDEX IX_ConvertedUsageTransaction_DateOfTransaction ON ConvertedUsageTransaction REBUILD WITH (ONLINE = OFF);
ALTER INDEX IX_ConvertedUsageTransaction_Application ON ConvertedUsageTransaction REBUILD WITH (ONLINE = OFF);
ALTER INDEX IX_ConvertedUsageTransaction_fkAccount ON ConvertedUsageTransaction REBUILD WITH (ONLINE = OFF);
ALTER INDEX IX_ConvertedUsageTransaction_SessionId ON ConvertedUsageTransaction REBUILD WITH (ONLINE = OFF);
ALTER INDEX PK_ConvertedUsageTransaction ON ConvertedUsageTransaction REBUILD WITH (ONLINE = OFF);

-- Shrink the database
DBCC SHINKDATABASE shrinkdatabase('AuditEvents_2018-10-21T00-00Z')